// generated by stringer -type PGState src/bitbucket.org/ulfurinn/blitz/blizzard; DO NOT EDIT

package blizzard

import "fmt"

const _PGState_name = "PGInitPGSpawningPGReadyPGHandoverPGTakeoverPGWaitingPGShutdown"

var _PGState_index = [...]uint8{6, 16, 23, 33, 43, 52, 62}

func (i PGState) String() string {
	if i < 0 || i >= PGState(len(_PGState_index)) {
		return fmt.Sprintf("PGState(%d)", i)
	}
	hi := _PGState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _PGState_index[i-1]
	}
	return _PGState_name[lo:hi]
}
