// generated by stringer -type ProcState src/bitbucket.org/ulfurinn/blitz/blizzard/; DO NOT EDIT

package blizzard

import "fmt"

const _ProcState_name = "ProcInitProcBootingProcReadyProcShuttingDownProcCollecting"

var _ProcState_index = [...]uint8{8, 19, 28, 44, 58}

func (i ProcState) String() string {
	if i < 0 || i >= ProcState(len(_ProcState_index)) {
		return fmt.Sprintf("ProcState(%d)", i)
	}
	hi := _ProcState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ProcState_index[i-1]
	}
	return _ProcState_name[lo:hi]
}
